version: '3.8'
services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development

  mobile:
    build: ./mobile
    ports:
      - "8080:8080"
    volumes:
      - ./mobile/lib:/app/lib